[package]
name = "database_api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
dotenv = "0.15.0"
serde = "1.0.127"
time = "0.3.1"
tokio-postgres = "0.7.2"
